#!/usr/bin/env bash
git init
git add .
read -p 'Enter branch name: ' branchName
git checkout -b "$branchName"
read -p 'Enter commit msg: ' commitMessage
git commit -m "Added $commitMessage"
git push -u origin "$branchName"

