#!/usr/bin/env bash
git init
git add .
currentBranch=git status
read -p 'Do you want to create new branch: ' ch
if [[ ch ]]; then
	read -p 'Enter branch name: ' branchName
	git checkout -b "$branchName"
	read -p 'Enter commit msg: ' commitMessage
	git commit -m "Added $commitMessage"
	git push -u origin "$branchName"
else
	read -p 'Enter commit msg: ' commitMessage
        git commit -m "Added $commitMessage"
	git push -u origin "$currentBranch"
fi
