#!/usr/bin/env bash

commitIt(){
	read -p 'Enter commit msg: ' commitMessage
        git commit -m "Added $commitMessage"
        git push -u origin "$currentBranch"

}
git init
git add .
currentBranch=$(git branch --show-current)
echo "$currentBranch"
read -p 'Do you want to create new branch (y/n) : ' ch
if [[ $ch == "y" ]]; then
	read -p 'Enter branch name: ' branchName
	git checkout -b "$branchName"
	commitIt
else
	echo "Continuing with $currentBranch"
	commitIt
fi
