#!/usr/bin/env bash

read data

echo "you said $data"


read -r data1
echo "You enetred $data1"

while read -r line; do
	echo "we read line $line"

done



#Notes: Important behavipr of bash
#read < ./inputs.txt #can also nread from this
#ehco name | xxd # ascii with 0a -> . -> new line
#echo -n name | xxd # ascii with -n no new line


ls gghg > file.txt 2>&1
